theme: jekyll-theme-hacker
title: How To Use GDB, The Gnu Project Debugger 
description: Linguagem de Programação 1
description: Instituto Metrópole Digital (IMD)
description: Universidade Federal do Rio Grande do Norte (UFRN)
