title: "How To Use GDB: The Gnu Project Debugger"
description: Linguagem de Programação 1
             Instituto Metrópole Digital (IMD)
             | Universidade Federal do Rio Grande do Norte (UFRN)

theme: jekyll-theme-cayman
